apiVersion: v1
kind: Pod
metadata:
  name: fraud-detection
  namespace: default
spec:
  runtimeClassName: kata-remote
  containers:
    - name: fraud-detection
      image: quay.io/confidential-devhub/signed/fraud-detection:latest
      env:
        - name: DECRYPTION_KEY_PATH
          value: kbs:///default/fraud-dataset/dataset_key
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
          - name: azure-sas-volume
            mountPath: "/azure/azure-sas"
  volumes:
    - name: azure-sas-volume
      secret:
        secretName: fraud-dataset-sas-sealed